'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const {
  getTierPolicyFromThemeSettings,
  resolveCustomerTier,
  resolveProductDiscount
} = require('../lib/tier-pricing-policy');
const {
  mergePublishedThemeSettings
} = require('../lib/theme-settings');

const schema = JSON.stringify([{
  name: 'Tier Pricing',
  settings: [
    { type: 'checkbox', id: 'tier_pricing_enabled', default: true },
    { type: 'select', id: 'tier_pricing_scope', default: 'all' },
    { type: 'text', id: 'tier_1_name', default: 'BLACK DIAMOND' },
    { type: 'text', id: 'tier_1_tag', default: 'BLACK DIAMOND' },
    { type: 'range', id: 'tier_1_discount', default: 15 },
    { type: 'text', id: 'tier_1_threshold', default: '20000' },
    { type: 'range', id: 'tier_2_discount', default: 12 },
    { type: 'text', id: 'tier_2_threshold', default: '3500' },
    { type: 'range', id: 'tier_3_discount', default: 10 },
    { type: 'text', id: 'tier_3_threshold', default: '1500' },
    { type: 'range', id: 'tier_4_discount', default: 8 },
    { type: 'text', id: 'tier_4_threshold', default: '500' },
    { type: 'range', id: 'tier_5_discount', default: 5 },
    { type: 'text', id: 'tier_5_threshold', default: '250' },
    { type: 'range', id: 'tier_6_discount', default: 0 },
    { type: 'checkbox', id: 'tier_prioritize_tags', default: true },
    { type: 'checkbox', id: 'tier_use_custom_metafield', default: true }
  ]
}]);

test('parser accepts Shopify comments and trailing commas', () => {
  const settings = mergePublishedThemeSettings(
    '/* generated */\n{"current":{"tier_1_discount":17,},}',
    '[{"settings":[{"id":"tier_1_discount","default":15,},],},]'
  );

  assert.equal(settings.tier_1_discount, 17);
});

test('published settings override schema defaults', () => {
  const data = `/* generated by Shopify */\n${JSON.stringify({
    current: {
      tier_2_discount: 14,
      tier_2_threshold: '4000',
      unrelated_setting: 'ignored'
    }
  })}`;
  const settings = mergePublishedThemeSettings(data, schema);

  assert.equal(settings.tier_1_discount, 15);
  assert.equal(settings.tier_2_discount, 14);
  assert.equal(settings.tier_2_threshold, '4000');
  assert.equal(settings.unrelated_setting, undefined);
});

test('policy uses the per-tier percentages from Theme Editor', () => {
  const data = JSON.stringify({
    current: {
      tier_1_discount: 21,
      tier_2_discount: 16,
      tier_3_discount: 13,
      tier_4_discount: 11,
      tier_5_discount: 8,
      tier_6_discount: 6,
      tier_prioritize_tags: true
    }
  });
  const settings = mergePublishedThemeSettings(data, schema);
  const policy = getTierPolicyFromThemeSettings(settings, {});

  assert.deepEqual(
    policy.tiers.map(tier => tier.discount),
    [21, 16, 13, 11, 8, 6]
  );
  assert.equal(
    resolveCustomerTier({ tags: ['DIAMOND'], amountSpent: { amount: '0' } }, policy).discount,
    16
  );
});

test('custom spend metafield setting matches Theme Editor behavior', () => {
  const data = JSON.stringify({
    current: {
      tier_prioritize_tags: false,
      tier_use_custom_metafield: false
    }
  });
  const settings = mergePublishedThemeSettings(data, schema);
  const policy = getTierPolicyFromThemeSettings(settings, {});
  const tier = resolveCustomerTier({
    tags: [],
    totalSpentMetafield: { value: '99999' },
    amountSpent: { amount: '300', currencyCode: 'USD' }
  }, policy);

  assert.equal(tier.name, 'SILVER');
});

test('disabled tier pricing returns no product discount', () => {
  const settings = mergePublishedThemeSettings(
    JSON.stringify({ current: { tier_pricing_enabled: false } }),
    schema
  );
  const policy = getTierPolicyFromThemeSettings(settings, {});

  assert.equal(policy.enabled, false);
  assert.equal(
    resolveProductDiscount(
      policy.tiers[0],
      ['tier-blackdiamond-99'],
      ['all-products'],
      policy
    ),
    0
  );
});
